default_stages: [commit]

default_language_version:
    python: python3.7

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    # Disabled due to pre-commit/pre-commit-hooks#159
    # -   id: check-docsgtring-first
    -   id: check-json
    -   id: check-merge-conflict
        stages: [commit]
    # Check merge conflict is not applied during rebase (no commit is done) so the issue can still be pushed
    -   id: check-merge-conflict
        args:
            - --assume-in-merge
        stages: [push]
    -   id: check-yaml
    -   id: check-toml
    -   id: check-xml
    -   id: no-commit-to-branch
        # Protect specific branches from direct checkins
        args: [--branch, main]
    -   id: debug-statements
    -   id: end-of-file-fixer
        # Override default [push, commit]
        stages: [commit]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        # Override default [push, commit]
        stages: [commit]
    -   id: fix-encoding-pragma
        args:
            - --remove
    # We should not add new tests to the legacy tests directory
    -   id: check-added-large-files
        alias: check-new-legacy-tests
        name: Check for new legacy tests
        args:
            - --maxkb=0
        files: ^etl\/.*\/test.*\.py
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.26.0
    hooks:
    -   id: pyupgrade
        args:
            # We need percent format for sentry
            - --keep-percent-format
            - --keep-runtime-typing
            - --py37-plus
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.9.3
    hooks:
    -   id: isort
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
-   repo: https://gitlab.com/pycqa/flake8
    # flake8 has to be placed after hooks modifying the code
    # (otherwise the reported line numbers would be inaccurate)
    rev: 4.0.1
    hooks:
      -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    # mypy has to be placed after hooks modifying the code
    # (otherwise the reported line numbers would be inaccurate)
    rev: v0.812
    hooks:
    -   id: mypy
        exclude: docs/legacy/source/conf.py
        additional_dependencies: [typing_extensions]
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/Kpler/kp-pre-commit-hooks
    rev: v0.0.7
    hooks:
      -   id: check-branch-linearity
      -   id: check-branch-name
      -   id: no-ephemeral-links
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v2.18.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.15.1
    hooks:
      - id: gitlint
-   repo: local
    hooks:
    -   id: check-model-import
        name: Check etl.orm.db_scheme import
        language: script
        entry: ./tools/check-model-import.sh
        types: [python]
-   repo: local
    hooks:
    -   id: check-alembic-graph-linearity
        name: Check for alembic graph linearity
        language: script
        entry: ./tools/alembic-history-linear.sh
        always_run: true
        pass_filenames: false
        stages: [push]
-   repo: local
    hooks:
    -   id: check-settings-usage
        name: Check settings.PLATFORM usage
        language: script
        entry: ./tools/check-platform-usage.sh
        types: [python]
