default_stages: [commit]

default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-json
    -   id: check-yaml
    -   id: check-toml
    -   id: check-xml
    -   id: debug-statements
    -   id: end-of-file-fixer
        # Override default [push, commit]
        stages: [commit]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
        # Override default [push, commit]
        stages: [commit]
    -   id: fix-encoding-pragma
        args:
            - --remove
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
        args:
            # We need percent format for sentry
            - --keep-percent-format
            - --keep-runtime-typing
            - --py310-plus
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.2.0
    hooks:
    -   id: forbid-crlf
    -   id: remove-crlf
-   repo: https://gitlab.com/pycqa/flake8
    # flake8 has to be placed after hooks modifying the code
    # (otherwise the reported line numbers would be inaccurate)
    rev: 3.9.2
    hooks:
      -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    # mypy has to be placed after hooks modifying the code
    # (otherwise the reported line numbers would be inaccurate)
    rev: v0.961
    hooks:
    -   id: mypy
        additional_dependencies: [typing_extensions]
-   repo: meta
    hooks:
    -   id: check-useless-excludes
